export const ADD_BOOK: "@@APP/ADD_BOOK" = "@@APP/ADD_BOOK";
export const ADD_ALL_BOOKS: "@@APP/ADD_ALL_BOOKS" = "@@APP/ADD_ALL_BOOKS";
export const FETCH_ALL_BOOKS: "@@APP/FETCH_ALL_BOOKS" = "@@APP/FETCH_ALL_BOOKS";
